"""schema changes

Revision ID: f3efaf984e47
Revises: 6ad87acfd973
Create Date: 2026-01-07 04:48:23.154889

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3efaf984e47'
down_revision = '6ad87acfd973'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campanhas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=160), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('imagem_url', sa.String(length=500), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campanhas_id'), 'campanhas', ['id'], unique=False)
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_id'), 'empresas', ['id'], unique=False)
    op.create_index(op.f('ix_empresas_nome'), 'empresas', ['nome'], unique=True)
    op.create_table('finance_categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_finance_categorias_id'), 'finance_categorias', ['id'], unique=False)
    op.create_table('finance_contas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_finance_contas_id'), 'finance_contas', ['id'], unique=False)
    op.create_table('finance_formas_pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_finance_formas_pagamento_id'), 'finance_formas_pagamento', ['id'], unique=False)
    op.create_table('materiais_apoio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=160), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('arquivo_url', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materiais_apoio_id'), 'materiais_apoio', ['id'], unique=False)
    op.create_table('usuarios_painel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_painel_cpf'), 'usuarios_painel', ['cpf'], unique=True)
    op.create_index(op.f('ix_usuarios_painel_email'), 'usuarios_painel', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_painel_id'), 'usuarios_painel', ['id'], unique=False)
    op.create_table('finance_lancamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descricao', sa.String(length=240), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('forma_pagamento_id', sa.Integer(), nullable=True),
    sa.Column('conta_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['finance_categorias.id'], ),
    sa.ForeignKeyConstraint(['conta_id'], ['finance_contas.id'], ),
    sa.ForeignKeyConstraint(['forma_pagamento_id'], ['finance_formas_pagamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_lancamentos_id'), 'finance_lancamentos', ['id'], unique=False)
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=200), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('celular', sa.String(length=11), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('endereco', sa.String(length=250), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('pergunta_seg', sa.String(length=200), nullable=False),
    sa.Column('resposta_seg_norm', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pacientes_cpf'), 'pacientes', ['cpf'], unique=True)
    op.create_index(op.f('ix_pacientes_id'), 'pacientes', ['id'], unique=False)
    op.create_table('acessos_app',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('evento', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acessos_app_id'), 'acessos_app', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_acessos_app_id'), table_name='acessos_app')
    op.drop_table('acessos_app')
    op.drop_index(op.f('ix_pacientes_id'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_cpf'), table_name='pacientes')
    op.drop_table('pacientes')
    op.drop_index(op.f('ix_finance_lancamentos_id'), table_name='finance_lancamentos')
    op.drop_table('finance_lancamentos')
    op.drop_index(op.f('ix_usuarios_painel_id'), table_name='usuarios_painel')
    op.drop_index(op.f('ix_usuarios_painel_email'), table_name='usuarios_painel')
    op.drop_index(op.f('ix_usuarios_painel_cpf'), table_name='usuarios_painel')
    op.drop_table('usuarios_painel')
    op.drop_index(op.f('ix_materiais_apoio_id'), table_name='materiais_apoio')
    op.drop_table('materiais_apoio')
    op.drop_index(op.f('ix_finance_formas_pagamento_id'), table_name='finance_formas_pagamento')
    op.drop_table('finance_formas_pagamento')
    op.drop_index(op.f('ix_finance_contas_id'), table_name='finance_contas')
    op.drop_table('finance_contas')
    op.drop_index(op.f('ix_finance_categorias_id'), table_name='finance_categorias')
    op.drop_table('finance_categorias')
    op.drop_index(op.f('ix_empresas_nome'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_id'), table_name='empresas')
    op.drop_table('empresas')
    op.drop_index(op.f('ix_campanhas_id'), table_name='campanhas')
    op.drop_table('campanhas')
    # ### end Alembic commands ###
